package com.example.budgettingtogether.storage.dto

import com.example.budgettingtogether.auth.UserPairing
import kotlinx.serialization.EncodeDefault
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@OptIn(ExperimentalSerializationApi::class)
@Serializable
data class UserPairingDto(
    // id is omitted on INSERT (auto-generated by Postgres BIGSERIAL)
    @SerialName("id")
    @EncodeDefault(EncodeDefault.Mode.NEVER)
    val id: Long? = null,

    @SerialName("requester_id") val requesterId: String,  // Supabase auth.users.id
    @SerialName("receiver_id")  val receiverId: String,   // Supabase auth.users.id
    @SerialName("status")       val status: String = UserPairing.STATUS_PENDING,
    @SerialName("created_at")   val createdAt: Long,

    @SerialName("accepted_at")
    @EncodeDefault(EncodeDefault.Mode.NEVER)
    val acceptedAt: Long? = null
) {
    fun toEntity() = UserPairing(
        id = id ?: 0,
        requesterId = requesterId,
        receiverId = receiverId,
        status = status,
        createdAt = createdAt,
        acceptedAt = acceptedAt
    )
}
