package com.example.budgettingtogether.currency

data class CurrencyInfo(val name: String, val symbol: String)

object CurrencyData {
    val currencies = mapOf(
        "AED" to CurrencyInfo("UAE Dirham", "د.إ"),
        "AFN" to CurrencyInfo("Afghan Afghani", "؋"),
        "ALL" to CurrencyInfo("Albanian Lek", "L"),
        "AMD" to CurrencyInfo("Armenian Dram", "֏"),
        "ANG" to CurrencyInfo("Netherlands Antillean Guilder", "ƒ"),
        "AOA" to CurrencyInfo("Angolan Kwanza", "Kz"),
        "ARS" to CurrencyInfo("Argentine Peso", "$"),
        "AUD" to CurrencyInfo("Australian Dollar", "A$"),
        "AWG" to CurrencyInfo("Aruban Florin", "ƒ"),
        "AZN" to CurrencyInfo("Azerbaijani Manat", "₼"),
        "BAM" to CurrencyInfo("Bosnia-Herzegovina Convertible Mark", "KM"),
        "BBD" to CurrencyInfo("Barbadian Dollar", "$"),
        "BDT" to CurrencyInfo("Bangladeshi Taka", "৳"),
        "BGN" to CurrencyInfo("Bulgarian Lev", "лв"),
        "BHD" to CurrencyInfo("Bahraini Dinar", ".د.ب"),
        "BIF" to CurrencyInfo("Burundian Franc", "FBu"),
        "BMD" to CurrencyInfo("Bermudan Dollar", "$"),
        "BND" to CurrencyInfo("Brunei Dollar", "$"),
        "BOB" to CurrencyInfo("Bolivian Boliviano", "Bs."),
        "BRL" to CurrencyInfo("Brazilian Real", "R$"),
        "BSD" to CurrencyInfo("Bahamian Dollar", "$"),
        "BTN" to CurrencyInfo("Bhutanese Ngultrum", "Nu."),
        "BWP" to CurrencyInfo("Botswanan Pula", "P"),
        "BYN" to CurrencyInfo("Belarusian Ruble", "Br"),
        "BZD" to CurrencyInfo("Belize Dollar", "$"),
        "CAD" to CurrencyInfo("Canadian Dollar", "C$"),
        "CDF" to CurrencyInfo("Congolese Franc", "FC"),
        "CHF" to CurrencyInfo("Swiss Franc", "CHF"),
        "CLP" to CurrencyInfo("Chilean Peso", "$"),
        "CNY" to CurrencyInfo("Chinese Yuan", "¥"),
        "COP" to CurrencyInfo("Colombian Peso", "$"),
        "CRC" to CurrencyInfo("Costa Rican Colón", "₡"),
        "CUP" to CurrencyInfo("Cuban Peso", "$"),
        "CVE" to CurrencyInfo("Cape Verdean Escudo", "$"),
        "CZK" to CurrencyInfo("Czech Koruna", "Kč"),
        "DJF" to CurrencyInfo("Djiboutian Franc", "Fdj"),
        "DKK" to CurrencyInfo("Danish Krone", "kr"),
        "DOP" to CurrencyInfo("Dominican Peso", "$"),
        "DZD" to CurrencyInfo("Algerian Dinar", "د.ج"),
        "EGP" to CurrencyInfo("Egyptian Pound", "E£"),
        "ERN" to CurrencyInfo("Eritrean Nakfa", "Nfk"),
        "ETB" to CurrencyInfo("Ethiopian Birr", "Br"),
        "EUR" to CurrencyInfo("Euro", "€"),
        "FJD" to CurrencyInfo("Fijian Dollar", "$"),
        "FKP" to CurrencyInfo("Falkland Islands Pound", "£"),
        "FOK" to CurrencyInfo("Faroese Króna", "kr"),
        "GBP" to CurrencyInfo("British Pound", "£"),
        "GEL" to CurrencyInfo("Georgian Lari", "₾"),
        "GGP" to CurrencyInfo("Guernsey Pound", "£"),
        "GHS" to CurrencyInfo("Ghanaian Cedi", "₵"),
        "GIP" to CurrencyInfo("Gibraltar Pound", "£"),
        "GMD" to CurrencyInfo("Gambian Dalasi", "D"),
        "GNF" to CurrencyInfo("Guinean Franc", "FG"),
        "GTQ" to CurrencyInfo("Guatemalan Quetzal", "Q"),
        "GYD" to CurrencyInfo("Guyanese Dollar", "$"),
        "HKD" to CurrencyInfo("Hong Kong Dollar", "HK$"),
        "HNL" to CurrencyInfo("Honduran Lempira", "L"),
        "HRK" to CurrencyInfo("Croatian Kuna", "kn"),
        "HTG" to CurrencyInfo("Haitian Gourde", "G"),
        "HUF" to CurrencyInfo("Hungarian Forint", "Ft"),
        "IDR" to CurrencyInfo("Indonesian Rupiah", "Rp"),
        "ILS" to CurrencyInfo("Israeli New Shekel", "₪"),
        "IMP" to CurrencyInfo("Isle of Man Pound", "£"),
        "INR" to CurrencyInfo("Indian Rupee", "₹"),
        "IQD" to CurrencyInfo("Iraqi Dinar", "ع.د"),
        "IRR" to CurrencyInfo("Iranian Rial", "﷼"),
        "ISK" to CurrencyInfo("Icelandic Króna", "kr"),
        "JEP" to CurrencyInfo("Jersey Pound", "£"),
        "JMD" to CurrencyInfo("Jamaican Dollar", "$"),
        "JOD" to CurrencyInfo("Jordanian Dinar", "د.ا"),
        "JPY" to CurrencyInfo("Japanese Yen", "¥"),
        "KES" to CurrencyInfo("Kenyan Shilling", "KSh"),
        "KGS" to CurrencyInfo("Kyrgystani Som", "с"),
        "KHR" to CurrencyInfo("Cambodian Riel", "៛"),
        "KID" to CurrencyInfo("Kiribati Dollar", "$"),
        "KMF" to CurrencyInfo("Comorian Franc", "CF"),
        "KRW" to CurrencyInfo("South Korean Won", "₩"),
        "KWD" to CurrencyInfo("Kuwaiti Dinar", "د.ك"),
        "KYD" to CurrencyInfo("Cayman Islands Dollar", "$"),
        "KZT" to CurrencyInfo("Kazakhstani Tenge", "₸"),
        "LAK" to CurrencyInfo("Laotian Kip", "₭"),
        "LBP" to CurrencyInfo("Lebanese Pound", "ل.ل"),
        "LKR" to CurrencyInfo("Sri Lankan Rupee", "Rs"),
        "LRD" to CurrencyInfo("Liberian Dollar", "$"),
        "LSL" to CurrencyInfo("Lesotho Loti", "L"),
        "LYD" to CurrencyInfo("Libyan Dinar", "ل.د"),
        "MAD" to CurrencyInfo("Moroccan Dirham", "د.م."),
        "MDL" to CurrencyInfo("Moldovan Leu", "L"),
        "MGA" to CurrencyInfo("Malagasy Ariary", "Ar"),
        "MKD" to CurrencyInfo("Macedonian Denar", "ден"),
        "MMK" to CurrencyInfo("Myanmar Kyat", "K"),
        "MNT" to CurrencyInfo("Mongolian Tugrik", "₮"),
        "MOP" to CurrencyInfo("Macanese Pataca", "MOP$"),
        "MRU" to CurrencyInfo("Mauritanian Ouguiya", "UM"),
        "MUR" to CurrencyInfo("Mauritian Rupee", "₨"),
        "MVR" to CurrencyInfo("Maldivian Rufiyaa", "Rf"),
        "MWK" to CurrencyInfo("Malawian Kwacha", "MK"),
        "MXN" to CurrencyInfo("Mexican Peso", "$"),
        "MYR" to CurrencyInfo("Malaysian Ringgit", "RM"),
        "MZN" to CurrencyInfo("Mozambican Metical", "MT"),
        "NAD" to CurrencyInfo("Namibian Dollar", "$"),
        "NGN" to CurrencyInfo("Nigerian Naira", "₦"),
        "NIO" to CurrencyInfo("Nicaraguan Córdoba", "C$"),
        "NOK" to CurrencyInfo("Norwegian Krone", "kr"),
        "NPR" to CurrencyInfo("Nepalese Rupee", "₨"),
        "NZD" to CurrencyInfo("New Zealand Dollar", "NZ$"),
        "OMR" to CurrencyInfo("Omani Rial", "ر.ع."),
        "PAB" to CurrencyInfo("Panamanian Balboa", "B/."),
        "PEN" to CurrencyInfo("Peruvian Sol", "S/"),
        "PGK" to CurrencyInfo("Papua New Guinean Kina", "K"),
        "PHP" to CurrencyInfo("Philippine Peso", "₱"),
        "PKR" to CurrencyInfo("Pakistani Rupee", "₨"),
        "PLN" to CurrencyInfo("Polish Zloty", "zł"),
        "PYG" to CurrencyInfo("Paraguayan Guarani", "₲"),
        "QAR" to CurrencyInfo("Qatari Rial", "ر.ق"),
        "RON" to CurrencyInfo("Romanian Leu", "lei"),
        "RSD" to CurrencyInfo("Serbian Dinar", "дин."),
        "RUB" to CurrencyInfo("Russian Ruble", "₽"),
        "RWF" to CurrencyInfo("Rwandan Franc", "FRw"),
        "SAR" to CurrencyInfo("Saudi Riyal", "ر.س"),
        "SBD" to CurrencyInfo("Solomon Islands Dollar", "$"),
        "SCR" to CurrencyInfo("Seychellois Rupee", "₨"),
        "SDG" to CurrencyInfo("Sudanese Pound", "ج.س."),
        "SEK" to CurrencyInfo("Swedish Krona", "kr"),
        "SGD" to CurrencyInfo("Singapore Dollar", "S$"),
        "SHP" to CurrencyInfo("Saint Helena Pound", "£"),
        "SLE" to CurrencyInfo("Sierra Leonean Leone", "Le"),
        "SOS" to CurrencyInfo("Somali Shilling", "Sh"),
        "SRD" to CurrencyInfo("Surinamese Dollar", "$"),
        "SSP" to CurrencyInfo("South Sudanese Pound", "£"),
        "STN" to CurrencyInfo("São Tomé and Príncipe Dobra", "Db"),
        "SYP" to CurrencyInfo("Syrian Pound", "£"),
        "SZL" to CurrencyInfo("Swazi Lilangeni", "L"),
        "THB" to CurrencyInfo("Thai Baht", "฿"),
        "TJS" to CurrencyInfo("Tajikistani Somoni", "ЅМ"),
        "TMT" to CurrencyInfo("Turkmenistani Manat", "m"),
        "TND" to CurrencyInfo("Tunisian Dinar", "د.ت"),
        "TOP" to CurrencyInfo("Tongan Paʻanga", "T$"),
        "TRY" to CurrencyInfo("Turkish Lira", "₺"),
        "TTD" to CurrencyInfo("Trinidad and Tobago Dollar", "$"),
        "TVD" to CurrencyInfo("Tuvaluan Dollar", "$"),
        "TWD" to CurrencyInfo("New Taiwan Dollar", "NT$"),
        "TZS" to CurrencyInfo("Tanzanian Shilling", "TSh"),
        "UAH" to CurrencyInfo("Ukrainian Hryvnia", "₴"),
        "UGX" to CurrencyInfo("Ugandan Shilling", "USh"),
        "USD" to CurrencyInfo("US Dollar", "$"),
        "UYU" to CurrencyInfo("Uruguayan Peso", "$"),
        "UZS" to CurrencyInfo("Uzbekistani Som", "сўм"),
        "VES" to CurrencyInfo("Venezuelan Bolívar", "Bs."),
        "VND" to CurrencyInfo("Vietnamese Dong", "₫"),
        "VUV" to CurrencyInfo("Vanuatu Vatu", "Vt"),
        "WST" to CurrencyInfo("Samoan Tala", "T"),
        "XAF" to CurrencyInfo("Central African CFA Franc", "FCFA"),
        "XCD" to CurrencyInfo("East Caribbean Dollar", "$"),
        "XOF" to CurrencyInfo("West African CFA Franc", "CFA"),
        "XPF" to CurrencyInfo("CFP Franc", "₣"),
        "YER" to CurrencyInfo("Yemeni Rial", "﷼"),
        "ZAR" to CurrencyInfo("South African Rand", "R"),
        "ZMW" to CurrencyInfo("Zambian Kwacha", "ZK"),
        "ZWL" to CurrencyInfo("Zimbabwean Dollar", "$")
    )

    fun getDisplayName(code: String): String {
        val info = currencies[code] ?: return code
        return "$code - ${info.name}"
    }

    fun getSymbol(code: String): String {
        return currencies[code]?.symbol ?: code
    }
}
